### ISSUE TITLE
Resizing window does not scale

### ISSUE THREAD

**Issue by RafaOP** [Team-Innis/UtH-Engine#14]
When the window is resized, objects in it are not scaled with the window and camera is not updated to the new middle of the screen.

**Comment by DrJonki** [comment]
This happens likely because window resize events aren't handled correctly and thus the view & viewport aren't reapplied.

I'd expect a fix sometime next week.

**Comment by DrJonki** [comment]
Resolved in 493f2b0ae0832fbc3fdb1f3b31f080b2d2219abe. Needs testing.
