### ISSUE TITLE
Refactor the Shader -class

### ISSUE THREAD

**Issue by ghost** [Team-Innis/UtH-Engine#18]
A change in syntax, from:

auto shader = new Shader();
shader->LoadShader("", "");
shader->Use();
uthEngine.GetWindow().SetShader(shader);

To something like:

Window& m_wnd = uthEngine.GetWindow();
...
m_wnd.SetShader(Shader::CreateAndUse("", ""));

**Comment by zeitt** [comment]
Seems uneccessary
