### ISSUE TITLE
In complete documentation

### ISSUE THREAD

**Issue by zeitt** [Team-Innis/UtH-Engine#24]
Should add way more content to wiki.

**Comment by zeitt** [comment]
everyone should do this one whenever they have time.

**Comment by DrJonki** [comment]
These pages are still nonexistent/incomplete, and I would hope the system's creator to write the respective wiki:
- ~~[AnimatedSprite](https://github.com/Team-Innis/UtH-Engine/wiki/Animated-Sprite)~~
- ~~[Text](https://github.com/Team-Innis/UtH-Engine/wiki/Text)~~
- ~~[Transform](https://github.com/Team-Innis/UtH-Engine/wiki/Transform)~~
- ~~[Tile maps](https://github.com/Team-Innis/UtH-Engine/wiki/Tilemaps)~~

I'll be finishing the following when I can (of course if anyone else wants to, they can as well):
- ~~[GameObject](https://github.com/Team-Innis/UtH-Engine/wiki/GameObject)~~
- ~~[Component](https://github.com/Team-Innis/UtH-Engine/wiki/Component)~~
- ~~[Render texture](https://github.com/Team-Innis/UtH-Engine/wiki/Render-Texture)~~

**Comment by Janzku** [comment]
[AnimatedSprite](https://github.com/Team-Innis/UtH-Engine/wiki/Animated-Sprite) completed.

**Comment by M4T1A5** [comment]
Added
- [Text](https://github.com/Team-Innis/UtH-Engine/wiki/Text)
- [Transform](https://github.com/Team-Innis/UtH-Engine/wiki/Transform)
- [Tile maps](https://github.com/Team-Innis/UtH-Engine/wiki/Tilemaps)
